In [16]:
import pandas as pd
import numpy as np
from IPython.display import display

In [17]:

datasets = {
    "hotel_bookings": "../data/raw/hotel_bookings.csv",
    "customers": "../data/raw/olist_customers_dataset.csv",
    "geolocation": "../data/raw/olist_geolocation_dataset.csv",
    "order_items": "../data/raw/olist_order_items_dataset.csv",
    "payments": "../data/raw/olist_order_payments_dataset.csv",
    "reviews": "../data/raw/olist_order_reviews_dataset.csv",
    "orders": "../data/raw/olist_orders_dataset.csv",
    "products": "../data/raw/olist_products_dataset.csv",
    "sellers": "../data/raw/olist_sellers_dataset.csv",
    "category_translation": "../data/raw/product_category_name_translation.csv"
}



dfs = {}

for name, path in datasets.items():
    dfs[name] = pd.read_csv(path)

def analyze_dataset(name, df):

    print("\n" + "="*120)
    print(f"DATASET: {name.upper()}")
    print("="*120)


    print("\n[1] SAMPLE DATA (10 ROWS)")

    sample_size = min(10, len(df))
    display(df.sample(sample_size))


    print("\n[2] DATA SHAPE")

    shape_df = pd.DataFrame({
        "Rows": [df.shape[0]],
        "Columns": [df.shape[1]]
    })

    display(shape_df)


    print("\n[3] DATA TYPES")

    dtype_df = pd.DataFrame({
        "Column": df.columns,
        "Data Type": df.dtypes.astype(str)
    })

    display(dtype_df)


    print("\n[4] DESCRIPTIVE STATISTICS")

    display(df.describe(include="all").T)

    print("\n[5] MISSING VALUES")

    missing_df = pd.DataFrame({
        "Missing Count": df.isnull().sum(),
        "Missing Percentage (%)":
            round(df.isnull().mean() * 100, 2)
    })

    missing_df = (
        missing_df
        .sort_values(
            by="Missing Percentage (%)",
            ascending=False
        )
    )

    display(missing_df)

    print("\n[6] DUPLICATED ROWS")

    duplicate_count = df.duplicated().sum()

    duplicate_df = pd.DataFrame({
        "Duplicate Rows": [duplicate_count],
        "Duplicate Percentage (%)": [
            round(
                duplicate_count / len(df) * 100,
                2
            )
        ]
    })

    display(duplicate_df)


    print("\n[7] CARDINALITY")

    cardinality_df = pd.DataFrame({
        "Unique Values": df.nunique()
    })

    cardinality_df = (
        cardinality_df
        .sort_values(
            by="Unique Values",
            ascending=False
        )
    )

    display(cardinality_df)


for name, df in dfs.items():
    analyze_dataset(name, df)

========================================================================================================================
DATASET: HOTEL_BOOKINGS
========================================================================================================================

[1] SAMPLE DATA (10 ROWS)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
17634,Resort Hotel,0,275,2015,October,41,4,4,10,2,...,No Deposit,314.0,NaN,0,Contract,47.33,0,0,Check-Out,2015-10-18
41581,City Hotel,0,1,2015,August,34,18,0,2,1,...,No Deposit,NaN,40.0,0,Transient,65.00,0,0,Check-Out,2015-08-20
74359,City Hotel,1,276,2015,July,30,20,1,1,2,...,No Deposit,1.0,NaN,0,Contract,62.00,0,0,Canceled,2015-01-01
23042,Resort Hotel,0,27,2016,November,48,22,0,2,1,...,No Deposit,NaN,154.0,0,Transient,27.00,0,0,Check-Out,2016-11-24
105395,City Hotel,0,3,2017,February,5,2,2,3,2,...,No Deposit,22.0,NaN,0,Transient,68.00,0,0,Check-Out,2017-02-07
108030,City Hotel,0,151,2017,March,12,20,1,1,2,...,No Deposit,37.0,NaN,0,Transient-Party,95.00,0,1,Check-Out,2017-03-22
109275,City Hotel,0,242,2017,April,14,5,0,4,2,...,No Deposit,7.0,NaN,0,Transient,87.03,0,3,Check-Out,2017-04-09
49407,City Hotel,1,78,2016,April,16,12,0,4,2,...,No Deposit,9.0,NaN,0,Transient,136.00,0,1,Canceled,2016-02-13
68292,City Hotel,1,104,2017,May,20,15,1,2,1,...,Non Refund,NaN,NaN,0,Transient,160.00,0,0,Canceled,2017-01-31
72522,City Hotel,1,158,2017,July,30,29,4,10,2,...,No Deposit,9.0,NaN,0,Transient,164.70,0,0,Canceled,2017-03-06

[2] DATA SHAPE

     Rows  Columns
0  119390       32

[3] DATA TYPES

                                                        Column Data Type
hotel                                                    hotel    object
is_canceled                                        is_canceled     int64
lead_time                                            lead_time     int64
arrival_date_year                            arrival_date_year     int64
arrival_date_month                          arrival_date_month    object
arrival_date_week_number              arrival_date_week_number     int64
arrival_date_day_of_month            arrival_date_day_of_month     int64
stays_in_weekend_nights                stays_in_weekend_nights     int64
stays_in_week_nights                      stays_in_week_nights     int64
adults                                                  adults     int64
children                                              children   float64
babies                                                  babies     int64
meal                                                      meal    object
country                                                country    object
market_segment                                  market_segment    object
distribution_channel                      distribution_channel    object
is_repeated_guest                            is_repeated_guest     int64
previous_cancellations                  previous_cancellations     int64
previous_bookings_not_canceled  previous_bookings_not_canceled     int64
reserved_room_type                          reserved_room_type    object
assigned_room_type                          assigned_room_type    object
booking_changes                                booking_changes     int64
deposit_type                                      deposit_type    object
agent                                                    agent   float64
company                                                company   float64
days_in_waiting_list                      days_in_waiting_list     int64
customer_type                                    customer_type    object
adr                                                        adr   float64
required_car_parking_spaces        required_car_parking_spaces     int64
total_of_special_requests            total_of_special_requests     int64
reservation_status                          reservation_status    object
reservation_status_date                reservation_status_date    object

[4] DESCRIPTIVE STATISTICS

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
hotel,119390,2,City Hotel,79330,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_canceled,119390.0,NaN,NaN,NaN,0.370416,0.482918,0.0,0.0,0.0,1.0,1.0
lead_time,119390.0,NaN,NaN,NaN,104.011416,106.863097,0.0,18.0,69.0,160.0,737.0
arrival_date_year,119390.0,NaN,NaN,NaN,2016.156554,0.707476,2015.0,2016.0,2016.0,2017.0,2017.0
arrival_date_month,119390,12,August,13877,NaN,NaN,NaN,NaN,NaN,NaN,NaN
arrival_date_week_number,119390.0,NaN,NaN,NaN,27.165173,13.605138,1.0,16.0,28.0,38.0,53.0
arrival_date_day_of_month,119390.0,NaN,NaN,NaN,15.798241,8.780829,1.0,8.0,16.0,23.0,31.0
stays_in_weekend_nights,119390.0,NaN,NaN,NaN,0.927599,0.998613,0.0,0.0,1.0,2.0,19.0
stays_in_week_nights,119390.0,NaN,NaN,NaN,2.500302,1.908286,0.0,1.0,2.0,3.0,50.0
adults,119390.0,NaN,NaN,NaN,1.856403,0.579261,0.0,2.0,2.0,2.0,55.0
children,119386.0,NaN,NaN,NaN,0.10389,0.398561,0.0,0.0,0.0,0.0,10.0
babies,119390.0,NaN,NaN,NaN,0.007949,0.097436,0.0,0.0,0.0,0.0,10.0
meal,119390,5,BB,92310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,118902,177,PRT,48590,NaN,NaN,NaN,NaN,NaN,NaN,NaN
market_segment,119390,8,Online TA,56477,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distribution_channel,119390,5,TA/TO,97870,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_repeated_guest,119390.0,NaN,NaN,NaN,0.031912,0.175767,0.0,0.0,0.0,0.0,1.0
previous_cancellations,119390.0,NaN,NaN,NaN,0.087118,0.844336,0.0,0.0,0.0,0.0,26.0
previous_bookings_not_canceled,119390.0,NaN,NaN,NaN,0.137097,1.497437,0.0,0.0,0.0,0.0,72.0
reserved_room_type,119390,10,A,85994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
assigned_room_type,119390,12,A,74053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
booking_changes,119390.0,NaN,NaN,NaN,0.221124,0.652306,0.0,0.0,0.0,0.0,21.0
deposit_type,119390,3,No Deposit,104641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
agent,103050.0,NaN,NaN,NaN,86.693382,110.774548,1.0,9.0,14.0,229.0,535.0
company,6797.0,NaN,NaN,NaN,189.266735,131.655015,6.0,62.0,179.0,270.0,543.0
days_in_waiting_list,119390.0,NaN,NaN,NaN,2.321149,17.594721,0.0,0.0,0.0,0.0,391.0
customer_type,119390,4,Transient,89613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adr,119390.0,NaN,NaN,NaN,101.831122,50.53579,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,NaN,NaN,NaN,0.062518,0.245291,0.0,0.0,0.0,0.0,8.0
total_of_special_requests,119390.0,NaN,NaN,NaN,0.571363,0.792798,0.0,0.0,0.0,1.0,5.0
reservation_status,119390,3,Check-Out,75166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reservation_status_date,119390,926,2015-10-21,1461,NaN,NaN,NaN,NaN,NaN,NaN,NaN

[5] MISSING VALUES

                                Missing Count  Missing Percentage (%)
company                                112593                   94.31
agent                                   16340                   13.69
country                                   488                    0.41
hotel                                       0                    0.00
arrival_date_month                          0                    0.00
arrival_date_week_number                    0                    0.00
lead_time                                   0                    0.00
is_canceled                                 0                    0.00
stays_in_weekend_nights                     0                    0.00
stays_in_week_nights                        0                    0.00
children                                    4                    0.00
adults                                      0                    0.00
babies                                      0                    0.00
meal                                        0                    0.00
arrival_date_day_of_month                   0                    0.00
arrival_date_year                           0                    0.00
distribution_channel                        0                    0.00
market_segment                              0                    0.00
previous_bookings_not_canceled              0                    0.00
is_repeated_guest                           0                    0.00
reserved_room_type                          0                    0.00
assigned_room_type                          0                    0.00
booking_changes                             0                    0.00
previous_cancellations                      0                    0.00
deposit_type                                0                    0.00
days_in_waiting_list                        0                    0.00
customer_type                               0                    0.00
adr                                         0                    0.00
required_car_parking_spaces                 0                    0.00
total_of_special_requests                   0                    0.00
reservation_status                          0                    0.00
reservation_status_date                     0                    0.00

[6] DUPLICATED ROWS

   Duplicate Rows  Duplicate Percentage (%)
0           31994                      26.8

[7] CARDINALITY

                                Unique Values
adr                                      8879
reservation_status_date                   926
lead_time                                 479
company                                   352
agent                                     333
country                                   177
days_in_waiting_list                      128
previous_bookings_not_canceled             73
arrival_date_week_number                   53
stays_in_week_nights                       35
arrival_date_day_of_month                  31
booking_changes                            21
stays_in_weekend_nights                    17
previous_cancellations                     15
adults                                     14
arrival_date_month                         12
assigned_room_type                         12
reserved_room_type                         10
market_segment                              8
total_of_special_requests                   6
children                                    5
meal                                        5
babies                                      5
distribution_channel                        5
required_car_parking_spaces                 5
customer_type                               4
arrival_date_year                           3
deposit_type                                3
reservation_status                          3
is_canceled                                 2
hotel                                       2
is_repeated_guest                           2

========================================================================================================================
DATASET: CUSTOMERS
========================================================================================================================

[1] SAMPLE DATA (10 ROWS)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
21697,e67cb1a64f6d90b3b8b9c78cdfe91dca,79296e3467d0afbe0e255170dbad2e21,55016,caruaru,PE
45136,a0d3e4c74c41e64fc0e34a1805a0f820,aac6c5c4314e4c2721df1440f0ede0fd,22713,rio de janeiro,RJ
9657,3e5f38e2c9b854ebada680e510dda33e,dbc64f4a749c106393e5ef492b07affa,43805,candeias,BA
28971,72d4958cd71988163a65a245caeae772,0c3ec1b0e0dbe9befcb520bc32ee7ef5,89266,jaragua do sul,SC
79044,2ee6a7340934c1c8c08bd9ec1187e919,51d027d6e0c06e327566e7be917890f8,2011,sao paulo,SP
81018,02035a6c43039fa299e0492df023bad2,e81e9d35d842afb8fc184b1ba90a7a74,6526,santana de parnaiba,SP
78083,d8aed8f8caaf359ef23d8084e816b12e,fefffc5e1f105d0b0a395a95dccff067,4122,sao paulo,SP
54137,c3d8c825f8b88801bcbd6034fd4e438b,814101b83b85436800244d9e0735c2b0,88067,florianopolis,SC
78256,a86fa41b9d57893b8b23ad9bf2b10427,132af74d1bd8b2b57807743c3f257081,27936,macae,RJ
38783,69d4bf26c29d3e86be7ab9126b9a7e4d,0a0bc01025ce6dbecc33717834faf717,22260,rio de janeiro,RJ

[2] DATA SHAPE

    Rows  Columns
0  99441        5

[3] DATA TYPES

                                            Column Data Type
customer_id                            customer_id    object
customer_unique_id              customer_unique_id    object
customer_zip_code_prefix  customer_zip_code_prefix     int64
customer_city                        customer_city    object
customer_state                      customer_state    object

[4] DESCRIPTIVE STATISTICS

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,99441,99441,274fa6071e5e17fe303b9748641082c8,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_unique_id,99441,96096,8d50f5eadf50201ccdcedfb9e2ac8455,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_zip_code_prefix,99441.0,NaN,NaN,NaN,35137.474583,29797.938996,1003.0,11347.0,24416.0,58900.0,99990.0
customer_city,99441,4119,sao paulo,15540,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_state,99441,27,SP,41746,NaN,NaN,NaN,NaN,NaN,NaN,NaN

[5] MISSING VALUES

                          Missing Count  Missing Percentage (%)
customer_id                           0                     0.0
customer_unique_id                    0                     0.0
customer_zip_code_prefix              0                     0.0
customer_city                         0                     0.0
customer_state                        0                     0.0

[6] DUPLICATED ROWS

   Duplicate Rows  Duplicate Percentage (%)
0               0                       0.0

[7] CARDINALITY

                          Unique Values
customer_id                       99441
customer_unique_id                96096
customer_zip_code_prefix          14994
customer_city                      4119
customer_state                       27

========================================================================================================================
DATASET: GEOLOCATION
========================================================================================================================

[1] SAMPLE DATA (10 ROWS)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
384366,18150,-23.651749,-47.222893,ibiuna,SP
69202,3952,-23.588250,-46.484376,sao paulo,SP
16601,1526,-23.568120,-46.630209,sao paulo,SP
420021,20921,-22.893287,-43.224970,rio de janeiro,RJ
991559,98300,-27.905134,-53.319991,palmeira das missões,RS
840037,79760,-22.295547,-53.270847,bataypora,MS
315444,13603,-22.343955,-47.401402,araras,SP
60390,3563,-23.542950,-46.496145,sao paulo,SP
300650,13339,-23.090850,-47.202102,indaiatuba,SP
988064,97542,-29.788291,-55.801634,alegrete,RS

[2] DATA SHAPE

      Rows  Columns
0  1000163        5

[3] DATA TYPES

                                                  Column Data Type
geolocation_zip_code_prefix  geolocation_zip_code_prefix     int64
geolocation_lat                          geolocation_lat   float64
geolocation_lng                          geolocation_lng   float64
geolocation_city                        geolocation_city    object
geolocation_state                      geolocation_state    object

[4] DESCRIPTIVE STATISTICS

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
geolocation_zip_code_prefix,1000163.0,NaN,NaN,NaN,36574.166466,30549.33571,1001.0,11075.0,26530.0,63504.0,99990.0
geolocation_lat,1000163.0,NaN,NaN,NaN,-21.176153,5.715866,-36.605374,-23.603546,-22.919377,-19.97962,45.065933
geolocation_lng,1000163.0,NaN,NaN,NaN,-46.390541,4.269748,-101.466766,-48.573172,-46.637879,-43.767709,121.105394
geolocation_city,1000163,8011,sao paulo,135800,NaN,NaN,NaN,NaN,NaN,NaN,NaN
geolocation_state,1000163,27,SP,404268,NaN,NaN,NaN,NaN,NaN,NaN,NaN

[5] MISSING VALUES

                             Missing Count  Missing Percentage (%)
geolocation_zip_code_prefix              0                     0.0
geolocation_lat                          0                     0.0
geolocation_lng                          0                     0.0
geolocation_city                         0                     0.0
geolocation_state                        0                     0.0

[6] DUPLICATED ROWS

   Duplicate Rows  Duplicate Percentage (%)
0          261831                     26.18

[7] CARDINALITY

                             Unique Values
geolocation_lng                     717613
geolocation_lat                     717360
geolocation_zip_code_prefix          19015
geolocation_city                      8011
geolocation_state                       27

========================================================================================================================
DATASET: ORDER_ITEMS
========================================================================================================================

[1] SAMPLE DATA (10 ROWS)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
83218,bcf9b1ea597cf15ce7c93eebfd3a915a,1,28fd7231afb14b368127513ae6ffe144,1835b56ce799e6a4dc4eddc053f04066,2017-12-06 01:31:20,21.99,15.10
42315,605fa1deddee0b912495c101e187f4e7,1,e168af8b2f0d9319737c6a7a37904f9e,3586b8580d9c917874e053a1bb37b5ff,2017-10-24 04:35:35,29.90,25.19
15588,239ac2c07beceefddb4e1017b9aabeda,1,3dd2a17168ec895c781a9191c1e95ad7,de722cd6dad950a92b7d4f82673f8833,2018-03-06 09:56:23,149.90,16.81
45398,6727a4e9eed7135cefc6d0f9de7f88a3,1,093f502d13b400c7acad57562017a149,d4e12e7884759a14fa0f5f896c791cae,2018-07-25 12:23:20,43.80,14.65
25261,397ce3ace09621efd4266efa5a17129c,1,0f9a07df17934769a978a9b2917ba8a3,c8b0e2b0a7095e5d8219575d5e7e1181,2018-06-18 20:31:48,199.99,12.42
1156,02b02f566c72d81744ae60c7b6afa22d,1,ccc61dc31608c5b78cf0cbe85582fb77,323ce52b5b81df2cd804b017b7f09aa7,2018-03-12 11:55:47,139.90,8.23
55625,7e7c209ab4d09fe584822fd6c054023d,1,04c4a4b9c924494fcf82e0fba966f955,86ccac0b835037332a596a33b6949ee1,2018-02-22 02:35:40,26.74,12.60
66922,98ffd20f7510aafde026fc41c46876b1,3,30ac6df06dc59ad72cf2f158fc2d904c,0dd184061fb0eaa7ca37932c68ab91c5,2018-04-12 11:55:18,120.00,24.74
55204,7d8cbe66ebd79f0202cc906a1dc9c91b,1,54b755678728b84472c2b654ac4de777,a3dd39f583bc80bd8c5901c95878921e,2017-12-12 00:30:32,39.90,42.38
81814,b9f64aec40db08ee03b99891f3bab687,1,bca0f349419cdf328a4fd6be5e99aa63,7722b1df1b0e383e000397b2c11e3e19,2018-04-05 23:30:17,84.90,24.72

[2] DATA SHAPE

     Rows  Columns
0  112650        7

[3] DATA TYPES

                                  Column Data Type
order_id                        order_id    object
order_item_id              order_item_id     int64
product_id                    product_id    object
seller_id                      seller_id    object
shipping_limit_date  shipping_limit_date    object
price                              price   float64
freight_value              freight_value   float64

[4] DESCRIPTIVE STATISTICS

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,112650,98666,8272b63d03f5f79c56e9e4120aec44ef,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_item_id,112650.0,NaN,NaN,NaN,1.197834,0.705124,1.0,1.0,1.0,1.0,21.0
product_id,112650,32951,aca2eb7d00ea1a7b8ebd4e68314663af,527,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_id,112650,3095,6560211a19b47992c3666cc44a7e94c0,2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipping_limit_date,112650,93318,2017-07-21 18:25:23,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,112650.0,NaN,NaN,NaN,120.653739,183.633928,0.85,39.9,74.99,134.9,6735.0
freight_value,112650.0,NaN,NaN,NaN,19.99032,15.806405,0.0,13.08,16.26,21.15,409.68

[5] MISSING VALUES

                     Missing Count  Missing Percentage (%)
order_id                         0                     0.0
order_item_id                    0                     0.0
product_id                       0                     0.0
seller_id                        0                     0.0
shipping_limit_date              0                     0.0
price                            0                     0.0
freight_value                    0                     0.0

[6] DUPLICATED ROWS

   Duplicate Rows  Duplicate Percentage (%)
0               0                       0.0

[7] CARDINALITY

                     Unique Values
order_id                     98666
shipping_limit_date          93318
product_id                   32951
freight_value                 6999
price                         5968
seller_id                     3095
order_item_id                   21

========================================================================================================================
DATASET: PAYMENTS
========================================================================================================================

[1] SAMPLE DATA (10 ROWS)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
47178,cea503481ea27c2c550bc48e007fc0a8,1,credit_card,1,42.53
64794,bff370f6b528410596f33e9bb8ccae83,1,credit_card,1,22.38
47945,69254704b1ebb61fa514636b0d51542b,1,credit_card,4,142.41
78280,ad5ad3658e7ba2b40e80f791dfb3dbb9,1,credit_card,6,67.53
11899,6c996c013efca89d881f5717239cf3b0,1,credit_card,2,114.70
7354,20e64aa65fbb0149e274381104f46bbe,1,credit_card,10,169.11
65249,a020433e87434b10e6dfc7a7ceb690c0,1,credit_card,2,137.45
60205,5f37c7c9cfd25572ee87b69b77f27b8c,1,credit_card,4,217.87
34704,090c44686a2c4ac5320b757784023c4b,1,credit_card,1,119.25
21546,a00f125175c8ff66e63dbacefe493aaf,1,credit_card,1,44.01

[2] DATA SHAPE

     Rows  Columns
0  103886        5

[3] DATA TYPES

                                    Column Data Type
order_id                          order_id    object
payment_sequential      payment_sequential     int64
payment_type                  payment_type    object
payment_installments  payment_installments     int64
payment_value                payment_value   float64

[4] DESCRIPTIVE STATISTICS

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,103886,99440,fa65dad1b0e818e3ccc5cb0e39231352,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_sequential,103886.0,NaN,NaN,NaN,1.092679,0.706584,1.0,1.0,1.0,1.0,29.0
payment_type,103886,5,credit_card,76795,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_installments,103886.0,NaN,NaN,NaN,2.853349,2.687051,0.0,1.0,1.0,4.0,24.0
payment_value,103886.0,NaN,NaN,NaN,154.10038,217.494064,0.0,56.79,100.0,171.8375,13664.08

[5] MISSING VALUES

                      Missing Count  Missing Percentage (%)
order_id                          0                     0.0
payment_sequential                0                     0.0
payment_type                      0                     0.0
payment_installments              0                     0.0
payment_value                     0                     0.0

[6] DUPLICATED ROWS

   Duplicate Rows  Duplicate Percentage (%)
0               0                       0.0

[7] CARDINALITY

                      Unique Values
order_id                      99440
payment_value                 29077
payment_sequential               29
payment_installments             24
payment_type                      5

========================================================================================================================
DATASET: REVIEWS
========================================================================================================================

[1] SAMPLE DATA (10 ROWS)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
41752,91315c6279d3a877698aad6e8c09cb0a,81fe59dfdb8538cc9b604380742323e4,4,NaN,NaN,2017-07-22 00:00:00,2017-07-26 21:40:19
21237,49d9aceef14b07faa2de03db6e734a8c,96d89a80126756983acb2d1bfbd97117,5,NaN,NaN,2018-08-28 00:00:00,2018-08-29 13:59:03
10609,61d602f2d5df413629dc8507c37a72ff,a0a2b9cdb28eba192410c480bdacc4fb,5,NaN,NaN,2018-04-11 00:00:00,2018-04-13 16:58:51
71240,6628914b152029fba77654057071eeac,ad0d46c22c5a9dd2699f5142b1882f5f,3,NaN,NaN,2017-02-11 00:00:00,2017-02-13 18:25:11
24041,7f7e3d48df444435f00284699ba6a4ac,9564498225916371a8670c3b0253ea81,1,NaN,Comprei 4 anilhas só chegou 1.,2017-05-31 00:00:00,2017-05-31 08:39:50
47690,fb51994d18bd81736daef43dea3fcf11,461a022953c6f3a8573e4e6a38a4d88d,5,NaN,Ja uso esses pneus a algum tempo \r\nMas com e...,2017-02-25 00:00:00,2017-02-26 13:07:50
20491,e57f346bb31aca9d3e316c7414f25b9e,f717c8f177b0e2927fb48196bc6b6383,5,NaN,NaN,2018-08-01 00:00:00,2018-08-04 16:56:26
87532,0d198f187cfdbee866dbd55b6bf2ab42,f5e55d131e51bd5f0dccc56c9096a951,1,Péssimo,"Paguei duas luminárias e recebi só uma, estou ...",2018-05-08 00:00:00,2018-05-10 12:42:20
84692,bb8616204916706741ad280a1711d4c5,a1cff9f46b83ac0fb525c755e46851f8,1,NaN,Não recebi o produto,2018-04-11 00:00:00,2018-04-11 14:03:40
16486,df6457a07c547a7e0eaa367367267a13,1d9a9731b9c10fc9cba74e6f74782e8b,5,NaN,NaN,2018-05-04 00:00:00,2018-05-04 19:04:18

[2] DATA SHAPE

    Rows  Columns
0  99224        7

[3] DATA TYPES

                                          Column Data Type
review_id                              review_id    object
order_id                                order_id    object
review_score                        review_score     int64
review_comment_title        review_comment_title    object
review_comment_message    review_comment_message    object
review_creation_date        review_creation_date    object
review_answer_timestamp  review_answer_timestamp    object

[4] DESCRIPTIVE STATISTICS

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
review_id,99224,98410,08528f70f579f0c830189efc523d2182,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_id,99224,98673,df56136b8031ecd28e200bb18e6ddb2e,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_score,99224.0,NaN,NaN,NaN,4.086421,1.347579,1.0,4.0,5.0,5.0,5.0
review_comment_title,11568,4527,Recomendo,423,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_comment_message,40977,36159,Muito bom,230,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_creation_date,99224,636,2017-12-19 00:00:00,463,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_answer_timestamp,99224,98248,2017-06-15 23:21:05,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

[5] MISSING VALUES

                         Missing Count  Missing Percentage (%)
review_comment_title             87656                   88.34
review_comment_message           58247                   58.70
review_id                            0                    0.00
review_score                         0                    0.00
order_id                             0                    0.00
review_creation_date                 0                    0.00
review_answer_timestamp              0                    0.00

[6] DUPLICATED ROWS

   Duplicate Rows  Duplicate Percentage (%)
0               0                       0.0

[7] CARDINALITY

                         Unique Values
order_id                         98673
review_id                        98410
review_answer_timestamp          98248
review_comment_message           36159
review_comment_title              4527
review_creation_date               636
review_score                         5

========================================================================================================================
DATASET: ORDERS
========================================================================================================================

[1] SAMPLE DATA (10 ROWS)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
54398,2b5d5c1847d069c5efeb82f4056c15d8,097c16abe2faea176ce88673499b5525,delivered,2018-08-07 17:47:15,2018-08-09 03:50:22,2018-08-09 16:11:00,2018-08-13 22:44:30,2018-08-20 00:00:00
98029,30e5fcd06cb431cd8941809a3f2f0f32,5e2695cadc5153ef2b56dd2ad1600622,delivered,2017-07-15 14:14:45,2017-07-15 14:25:13,2017-07-20 16:43:37,2017-07-25 18:52:26,2017-08-08 00:00:00
22213,04b7f4eff7b30fc23df0be1f249113a5,97b1a3ce290922863b4118a8a290d3bd,delivered,2018-07-30 10:59:07,2018-07-30 11:40:04,2018-07-31 15:22:00,2018-08-04 12:55:49,2018-08-10 00:00:00
71918,88fb267a50efb599d94ac61abec346b0,69516ffcc9deb07156b30e97c0573919,delivered,2018-05-07 16:36:48,2018-05-07 17:56:22,2018-05-08 14:04:00,2018-05-11 23:07:41,2018-05-23 00:00:00
19545,27c23f89fe3b1bb3b137c7be5ae8407e,1bde0d4e3110504dff1154416342f246,delivered,2018-01-06 09:15:53,2018-01-09 07:25:40,2018-02-15 15:06:02,2018-02-27 17:07:58,2018-03-13 00:00:00
12457,40ef39d72e573867de1282d22b03b6be,74167fa986badc6600b60439162a8619,delivered,2018-02-13 14:40:56,2018-02-13 15:07:55,2018-02-19 17:51:26,2018-02-26 21:57:48,2018-03-06 00:00:00
44906,d9258776ebce96efd9811c6554d12726,1ead19a592ff7cb342e088c257c1f45d,canceled,2017-10-20 19:35:47,NaN,NaN,NaN,2017-11-16 00:00:00
17859,e5b2ffcb8f2da06d6e3c42b180a41a5e,222686e9bc3bee00511c05f3c4c9e64f,delivered,2017-04-14 14:31:25,2017-04-14 14:41:50,2017-04-18 11:24:48,2017-04-29 10:04:31,2017-05-10 00:00:00
28138,b13ee329a2e6ec2e8f32c1e64e77796e,8b084e41a2342a54666d2317348d5db3,delivered,2017-08-27 20:25:44,2017-08-29 04:44:38,2017-08-30 09:22:18,2017-09-13 15:37:08,2017-09-25 00:00:00
30595,e7ad5555cd68853b98cff91be575f605,01f1dc6000f77f9b0807f01ebde9ec12,delivered,2017-12-27 23:41:28,2017-12-27 23:50:22,2017-12-28 17:29:01,2017-12-30 01:17:04,2018-01-16 00:00:00

[2] DATA SHAPE

    Rows  Columns
0  99441        8

[3] DATA TYPES

                                                      Column Data Type
order_id                                            order_id    object
customer_id                                      customer_id    object
order_status                                    order_status    object
order_purchase_timestamp            order_purchase_timestamp    object
order_approved_at                          order_approved_at    object
order_delivered_carrier_date    order_delivered_carrier_date    object
order_delivered_customer_date  order_delivered_customer_date    object
order_estimated_delivery_date  order_estimated_delivery_date    object

[4] DESCRIPTIVE STATISTICS

,count,unique,top,freq
order_id,99441,99441,66dea50a8b16d9b4dee7af250b4be1a5,1
customer_id,99441,99441,edb027a75a1449115f6b43211ae02a24,1
order_status,99441,8,delivered,96478
order_purchase_timestamp,99441,98875,2018-08-02 12:05:26,3
order_approved_at,99281,90733,2018-02-27 04:31:10,9
order_delivered_carrier_date,97658,81018,2018-05-09 15:48:00,47
order_delivered_customer_date,96476,95664,2018-05-08 19:36:48,3
order_estimated_delivery_date,99441,459,2017-12-20 00:00:00,522

[5] MISSING VALUES

                               Missing Count  Missing Percentage (%)
order_delivered_customer_date           2965                    2.98
order_delivered_carrier_date            1783                    1.79
order_approved_at                        160                    0.16
order_id                                   0                    0.00
order_purchase_timestamp                   0                    0.00
order_status                               0                    0.00
customer_id                                0                    0.00
order_estimated_delivery_date              0                    0.00

[6] DUPLICATED ROWS

   Duplicate Rows  Duplicate Percentage (%)
0               0                       0.0

[7] CARDINALITY

                               Unique Values
order_id                               99441
customer_id                            99441
order_purchase_timestamp               98875
order_delivered_customer_date          95664
order_approved_at                      90733
order_delivered_carrier_date           81018
order_estimated_delivery_date            459
order_status                               8

========================================================================================================================
DATASET: PRODUCTS
========================================================================================================================

[1] SAMPLE DATA (10 ROWS)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
19684,7d88ffedac5a08939ab9b5fbbc6b61ba,bebes,19.0,1245.0,4.0,1000.0,25.0,10.0,30.0
20894,9d838a7fbaba7fca5f1fad259984063a,informatica_acessorios,47.0,1076.0,1.0,117.0,16.0,16.0,11.0
26138,7638edba4cfcace983ea5ebf8f9a8244,informatica_acessorios,37.0,946.0,1.0,393.0,28.0,13.0,23.0
2507,08922ac36480e00c6972216735d44693,relogios_presentes,55.0,184.0,6.0,300.0,16.0,2.0,11.0
10736,f6192c622ef0023ec493f1929d602176,cama_mesa_banho,47.0,339.0,1.0,100.0,16.0,26.0,26.0
7346,4d88bf79cfba786c4f220da5869dbd0b,cool_stuff,42.0,1022.0,3.0,3533.0,37.0,53.0,44.0
12665,4c6aedb2bfbcb47f59db757dfc22c607,artes,55.0,2021.0,7.0,700.0,19.0,5.0,20.0
22700,13c1b4c5f9f4eb68afa4132342e73777,beleza_saude,36.0,862.0,1.0,460.0,24.0,14.0,18.0
10095,947c79ffdc05997e940df6e00bc8a82e,beleza_saude,20.0,79.0,1.0,204.0,18.0,18.0,18.0
30597,59003ff3120537147fec3f06e92cd920,cool_stuff,55.0,1080.0,3.0,400.0,20.0,16.0,19.0

[2] DATA SHAPE

    Rows  Columns
0  32951        9

[3] DATA TYPES

                                                Column Data Type
product_id                                  product_id    object
product_category_name            product_category_name    object
product_name_lenght                product_name_lenght   float64
product_description_lenght  product_description_lenght   float64
product_photos_qty                  product_photos_qty   float64
product_weight_g                      product_weight_g   float64
product_length_cm                    product_length_cm   float64
product_height_cm                    product_height_cm   float64
product_width_cm                      product_width_cm   float64

[4] DESCRIPTIVE STATISTICS

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
product_id,32951,32951,106392145fca363410d287a815be6de4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_category_name,32341,73,cama_mesa_banho,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_name_lenght,32341.0,NaN,NaN,NaN,48.476949,10.245741,5.0,42.0,51.0,57.0,76.0
product_description_lenght,32341.0,NaN,NaN,NaN,771.495285,635.115225,4.0,339.0,595.0,972.0,3992.0
product_photos_qty,32341.0,NaN,NaN,NaN,2.188986,1.736766,1.0,1.0,1.0,3.0,20.0
product_weight_g,32949.0,NaN,NaN,NaN,2276.472488,4282.038731,0.0,300.0,700.0,1900.0,40425.0
product_length_cm,32949.0,NaN,NaN,NaN,30.815078,16.914458,7.0,18.0,25.0,38.0,105.0
product_height_cm,32949.0,NaN,NaN,NaN,16.937661,13.637554,2.0,8.0,13.0,21.0,105.0
product_width_cm,32949.0,NaN,NaN,NaN,23.196728,12.079047,6.0,15.0,20.0,30.0,118.0

[5] MISSING VALUES

                            Missing Count  Missing Percentage (%)
product_category_name                 610                    1.85
product_description_lenght            610                    1.85
product_name_lenght                   610                    1.85
product_photos_qty                    610                    1.85
product_weight_g                        2                    0.01
product_height_cm                       2                    0.01
product_length_cm                       2                    0.01
product_width_cm                        2                    0.01
product_id                              0                    0.00

[6] DUPLICATED ROWS

   Duplicate Rows  Duplicate Percentage (%)
0               0                       0.0

[7] CARDINALITY

                            Unique Values
product_id                          32951
product_description_lenght           2960
product_weight_g                     2204
product_height_cm                     102
product_length_cm                      99
product_width_cm                       95
product_category_name                  73
product_name_lenght                    66
product_photos_qty                     19

========================================================================================================================
DATASET: SELLERS
========================================================================================================================

[1] SAMPLE DATA (10 ROWS)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
2955,46dc3b2cc0980fb8ec44634e21d2718e,22240,rio de janeiro,RJ
1256,e76ecc7e9a1a1e3c6df9d2a8261c423d,30140,belo horizonte,MG
2694,cb3dd9ce66268c7a3ca7241ac70ab58c,3028,sao paulo,SP
457,714b9a1332840f257b49f476bea4e341,15910,monte alto,SP
1727,c4d51195486dc781531876a7d00453d8,19023,presidente prudente,SP
94,83353a83fd769dfafa4f21a72b15e3e5,5786,sao paulo,SP
1703,7b7ed56ae755e2880f2b69632e839c1e,74230,goiania,GO
333,32f83ffe11cd40f7adcf4eef171f52d9,97502,uruguaiana,RS
1116,270572bb714b00531be85e16e1550f26,9370,maua,SP
1776,90b57083da5d803237da74daec6dcb2b,80730,curitiba,PR

[2] DATA SHAPE

   Rows  Columns
0  3095        4

[3] DATA TYPES

                                        Column Data Type
seller_id                            seller_id    object
seller_zip_code_prefix  seller_zip_code_prefix     int64
seller_city                        seller_city    object
seller_state                      seller_state    object

[4] DESCRIPTIVE STATISTICS

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
seller_id,3095,3095,9e25199f6ef7e7c347120ff175652c3b,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_zip_code_prefix,3095.0,NaN,NaN,NaN,32291.059451,32713.45383,1001.0,7093.5,14940.0,64552.5,99730.0
seller_city,3095,611,sao paulo,694,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_state,3095,23,SP,1849,NaN,NaN,NaN,NaN,NaN,NaN,NaN

[5] MISSING VALUES

                        Missing Count  Missing Percentage (%)
seller_id                           0                     0.0
seller_zip_code_prefix              0                     0.0
seller_city                         0                     0.0
seller_state                        0                     0.0

[6] DUPLICATED ROWS

   Duplicate Rows  Duplicate Percentage (%)
0               0                       0.0

[7] CARDINALITY

                        Unique Values
seller_id                        3095
seller_zip_code_prefix           2246
seller_city                       611
seller_state                       23

========================================================================================================================
DATASET: CATEGORY_TRANSLATION
========================================================================================================================

[1] SAMPLE DATA (10 ROWS)

   product_category_name product_category_name_english
61                musica                         music
21      fashion_calcados                 fashion_shoes
8              telefonia                     telephony
58               bebidas                        drinks
16    ferramentas_jardim                  garden_tools
14            brinquedos                          toys
34     artigos_de_festas                party_supplies
22            cool_stuff                    cool_stuff
39       livros_tecnicos               books_technical
32           eletronicos                   electronics

[2] DATA SHAPE

   Rows  Columns
0    71        2

[3] DATA TYPES

                                                      Column Data Type
product_category_name                  product_category_name    object
product_category_name_english  product_category_name_english    object

[4] DESCRIPTIVE STATISTICS

                              count unique            top freq
product_category_name            71     71   beleza_saude    1
product_category_name_english    71     71  health_beauty    1

[5] MISSING VALUES

                               Missing Count  Missing Percentage (%)
product_category_name                      0                     0.0
product_category_name_english              0                     0.0

[6] DUPLICATED ROWS

   Duplicate Rows  Duplicate Percentage (%)
0               0                       0.0

[7] CARDINALITY

                               Unique Values
product_category_name                     71
product_category_name_english             71

## Why Use .copy() When Creating DataFrames?

Ban đầu dữ liệu được gán như sau:

```python
hotel_df = dfs["hotel_bookings"]
```

Cách gán này không tạo ra một DataFrame mới mà chỉ tạo một tham chiếu (reference) tới cùng một đối tượng DataFrame trong bộ nhớ.

Do đó, mọi thay đổi thực hiện trên `hotel_df` sẽ đồng thời làm thay đổi `dfs["hotel_bookings"]`.

Ví dụ:

```python
hotel_df.drop(columns=["company"], inplace=True)
```

Sau lệnh trên, cột `company` cũng bị xóa khỏi `dfs["hotel_bookings"]`.

Để tránh làm thay đổi dữ liệu gốc (raw data), cần sử dụng phương thức `.copy()`:

```python
hotel_df = dfs["hotel_bookings"].copy()
```

Khi đó, `hotel_df` trở thành một bản sao độc lập của dữ liệu gốc. Mọi thao tác làm sạch dữ liệu chỉ ảnh hưởng tới `hotel_df` mà không làm thay đổi `dfs["hotel_bookings"]`.

Việc sử dụng `.copy()` giúp:

* Bảo toàn dữ liệu gốc để đối chiếu khi cần.
* Đảm bảo kết quả EDA luôn được thực hiện trên dữ liệu nguyên bản.
* Tránh các lỗi phát sinh do vô tình thay đổi dữ liệu trong quá trình tiền xử lý.
* Tách biệt rõ ràng giữa dữ liệu thô (raw data) và dữ liệu đã làm sạch (clean data).

In [18]:
hotel_df = dfs["hotel_bookings"].copy()
customers_df = dfs["customers"].copy()
geolocation_df = dfs["geolocation"].copy()
order_items_df = dfs["order_items"].copy()
payments_df = dfs["payments"].copy()
reviews_df = dfs["reviews"].copy()
orders_df = dfs["orders"].copy()
products_df = dfs["products"].copy()
sellers_df = dfs["sellers"].copy()
category_df = dfs["category_translation"].copy()

## Handling Missing Values in Hotel Booking Dataset

Trong quá trình khám phá dữ liệu, bảng `hotel_bookings` xuất hiện một số cột chứa giá trị thiếu (missing values). Các phương pháp xử lý được lựa chọn dựa trên ý nghĩa nghiệp vụ của từng thuộc tính:

* **company**: Cột này có tỷ lệ thiếu rất cao (94.31%), do đó được loại bỏ khỏi tập dữ liệu vì không mang lại nhiều giá trị cho phân tích và mô hình học máy.
* **agent**: Giá trị thiếu được thay thế bằng `0`, biểu thị khách hàng không đặt phòng thông qua đại lý du lịch.
* **country**: Giá trị thiếu được thay thế bằng `"Unknown"` nhằm giữ lại toàn bộ bản ghi và phản ánh rõ các trường hợp không xác định quốc gia.
* **children**: Giá trị thiếu được thay thế bằng `0`, giả định rằng khách hàng không đi cùng trẻ em trong các trường hợp dữ liệu bị thiếu.

Sau khi xử lý, tập dữ liệu không còn giá trị thiếu ở các cột trên và sẵn sàng cho các bước phân tích và xây dựng mô hình tiếp theo.

In [19]:

hotel_df.drop(columns=["company"], inplace=True)

hotel_df["agent"] = hotel_df["agent"].fillna(0)

hotel_df["country"] = hotel_df["country"].fillna("Unknown")

hotel_df["children"] = hotel_df["children"].fillna(0)

In [20]:
hotel_df.duplicated().sum()

np.int64(32001)

## Handling Missing Values in Review Dataset

Bảng `olist_order_reviews_dataset` chứa hai cột văn bản là `review_comment_title` và `review_comment_message` với tỷ lệ giá trị thiếu khá cao. Tuy nhiên, các giá trị thiếu này không phải là lỗi dữ liệu mà phản ánh trường hợp khách hàng chỉ đánh giá bằng số sao mà không để lại nhận xét bằng văn bản.

Do đó, thay vì xóa các bản ghi hoặc loại bỏ cột, các giá trị thiếu được thay thế bằng:

* `No Title` đối với cột `review_comment_title`
* `No Message` đối với cột `review_comment_message`

Cách xử lý này giúp bảo toàn toàn bộ dữ liệu đánh giá và hỗ trợ cho các bước phân tích văn bản hoặc xây dựng mô hình học máy trong tương lai.

In [21]:
reviews_df["review_comment_title"] = (
    reviews_df["review_comment_title"]
    .fillna("No Title")
)

reviews_df["review_comment_message"] = (
    reviews_df["review_comment_message"]
    .fillna("No Message")
)

## Converting Date Columns to Datetime

Các cột thời gian trong bảng `orders` được chuyển từ kiểu dữ liệu `object` sang `datetime` để hỗ trợ việc phân tích dữ liệu theo thời gian, tính toán thời gian giao hàng và xây dựng đặc trưng cho các mô hình học máy.

Các cột được chuyển đổi bao gồm:

* order_purchase_timestamp
* order_approved_at
* order_delivered_carrier_date
* order_delivered_customer_date
* order_estimated_delivery_date

Trong quá trình chuyển đổi, các giá trị không hợp lệ sẽ được tự động chuyển thành `NaT` bằng tham số `errors='coerce'`.


## Handling Missing Values in Order Date Columns

Trong bảng `orders`, ba cột `order_approved_at`, `order_delivered_carrier_date` và `order_delivered_customer_date` xuất hiện một số giá trị thiếu. Sau khi kiểm tra mối quan hệ với thuộc tính `order_status`, nhận thấy các giá trị thiếu này chủ yếu xuất hiện ở những đơn hàng có trạng thái như `canceled`, `unavailable`, `created` hoặc các đơn hàng chưa hoàn tất quy trình xử lý.

Do đó, các giá trị thiếu này không phải là lỗi dữ liệu mà phản ánh đúng trạng thái thực tế của đơn hàng trong hệ thống:

* `order_approved_at`: Đơn hàng chưa được xác nhận thanh toán hoặc bị hủy trước khi hoàn tất quá trình phê duyệt.
* `order_delivered_carrier_date`: Đơn hàng chưa được bàn giao cho đơn vị vận chuyển.
* `order_delivered_customer_date`: Đơn hàng chưa được giao thành công cho khách hàng.

Việc thay thế các giá trị thiếu bằng một ngày giả định có thể làm sai lệch bản chất nghiệp vụ của dữ liệu và ảnh hưởng đến các phân tích liên quan đến thời gian xử lý, vận chuyển và giao hàng. Vì vậy, các giá trị thiếu trong ba cột này được giữ nguyên để đảm bảo tính chính xác và toàn vẹn của dữ liệu.

In [22]:
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

orders_df[date_columns] = orders_df[date_columns].apply(
    pd.to_datetime,
    errors='coerce'
)

display(
    pd.DataFrame({
        "Column": date_columns,
        "Data Type": orders_df[date_columns].dtypes.astype(str)
    })
)

                                                      Column       Data Type
order_purchase_timestamp            order_purchase_timestamp  datetime64[ns]
order_approved_at                          order_approved_at  datetime64[ns]
order_delivered_carrier_date    order_delivered_carrier_date  datetime64[ns]
order_delivered_customer_date  order_delivered_customer_date  datetime64[ns]
order_estimated_delivery_date  order_estimated_delivery_date  datetime64[ns]

In [23]:
orders_df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

## Handling Missing Values in Product Dataset

Các giá trị thiếu trong bảng sản phẩm được xử lý dựa trên bản chất của từng thuộc tính.

* `product_category_name` được thay thế bằng `"Unknown Category"` nhằm biểu diễn các sản phẩm chưa xác định được danh mục.
* `product_name_lenght`, `product_description_lenght` và `product_photos_qty` được thay thế bằng giá trị `0`, phản ánh trường hợp sản phẩm không có tên, không có mô tả hoặc không có hình ảnh.
* Các thuộc tính vật lý của sản phẩm gồm `product_weight_g`, `product_length_cm`, `product_height_cm` và `product_width_cm` được thay thế bằng giá trị trung vị (Median). Phương pháp này giúp giảm ảnh hưởng của các giá trị ngoại lai và duy trì phân bố dữ liệu gần với thực tế.

Sau khi xử lý, tập dữ liệu không còn giá trị thiếu và sẵn sàng cho các bước phân tích và xây dựng mô hình học máy.

In [24]:
products_df['product_category_name'] = (
    products_df['product_category_name']
    .fillna('Unknown Category')
)


products_df['product_name_lenght'] = (
    products_df['product_name_lenght']
    .fillna(0)
)

products_df['product_description_lenght'] = (
    products_df['product_description_lenght']
    .fillna(0)
)

products_df['product_photos_qty'] = (
    products_df['product_photos_qty']
    .fillna(0)
)

physical_cols = [
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]

for col in physical_cols:
    products_df[col] = products_df[col].fillna(
        products_df[col].median()
    )

In [25]:
for name, df in {
    "hotel": hotel_df,
    "reviews": reviews_df,
    "orders": orders_df,
    "products": products_df
}.items():

    print(f"\n{name.upper()}")
    print(df.isnull().sum()[df.isnull().sum() > 0])

HOTEL
Series([], dtype: int64)

REVIEWS
Series([], dtype: int64)

ORDERS
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

PRODUCTS
Series([], dtype: int64)

In [26]:
for name, df in dfs.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

hotel_bookings: 31994 duplicate rows
customers: 0 duplicate rows
geolocation: 261831 duplicate rows
order_items: 0 duplicate rows
payments: 0 duplicate rows
reviews: 0 duplicate rows
orders: 0 duplicate rows
products: 0 duplicate rows
sellers: 0 duplicate rows
category_translation: 0 duplicate rows

## Handling Duplicate Records

Sau khi kiểm tra dữ liệu, chỉ có hai bảng xuất hiện số lượng lớn bản ghi trùng lặp là `hotel_bookings` và `geolocation`.

### Hotel Bookings Dataset

Bảng `hotel_bookings` chứa khoảng 31,994 bản ghi trùng lặp hoàn toàn. Tuy nhiên, các bản ghi này được **giữ nguyên** và không bị loại bỏ.

Lý do là tập dữ liệu không cung cấp khóa định danh duy nhất (Booking ID) cho từng lượt đặt phòng. Do đó, không thể khẳng định các bản ghi giống nhau là dữ liệu lỗi. Trong thực tế, nhiều khách hàng khác nhau có thể thực hiện các đặt phòng với cùng khách sạn, thời gian lưu trú, số lượng khách, giá phòng và trạng thái đặt phòng, dẫn đến các bản ghi có giá trị hoàn toàn giống nhau.

Việc loại bỏ các bản ghi này có thể làm mất các giao dịch hợp lệ, ảnh hưởng đến phân tích kinh doanh và làm thay đổi phân phối dữ liệu khi xây dựng mô hình Machine Learning. Vì vậy, các bản ghi trùng lặp trong bảng `hotel_bookings` được giữ lại.

### Geolocation Dataset

Bảng `geolocation` chứa khoảng 261,831 bản ghi trùng lặp hoàn toàn. Các bản ghi này được **loại bỏ** bằng phương pháp `drop_duplicates()`.

Khác với bảng đặt phòng, bảng `geolocation` là bảng dữ liệu tham chiếu địa lý, bao gồm mã vùng bưu chính, tọa độ địa lý và thông tin vị trí. Nhiều dòng trong bảng chứa chính xác cùng một thông tin về mã vùng, kinh độ, vĩ độ, thành phố và bang.

Các bản ghi trùng lặp này không mang thêm thông tin mới cho quá trình phân tích, đồng thời làm tăng kích thước dữ liệu và thời gian xử lý. Việc loại bỏ chúng giúp giảm dung lượng tập dữ liệu, tăng hiệu quả xử lý và không làm mất bất kỳ thông tin nghiệp vụ quan trọng nào.

### Conclusion

* Giữ nguyên các bản ghi trùng lặp trong bảng `hotel_bookings`.
* Loại bỏ các bản ghi trùng lặp trong bảng `geolocation`.
* Các bảng còn lại không chứa bản ghi trùng lặp nên không cần xử lý thêm.

In [27]:
geolocation_df.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [28]:
duplicate_geo = geolocation_df[
    geolocation_df.duplicated()
]

display(duplicate_geo.head())

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
15,1046,-23.546081,-46.644820,sao paulo,SP
44,1046,-23.546081,-46.644820,sao paulo,SP
65,1046,-23.546081,-46.644820,sao paulo,SP
66,1009,-23.546935,-46.636588,sao paulo,SP
67,1046,-23.546081,-46.644820,sao paulo,SP

In [29]:
geolocation_df.drop_duplicates(inplace=True)

In [30]:
for name, df in {
    "hotel": hotel_df,
    "customers": customers_df,
    "geolocation": geolocation_df,
    "order_items": order_items_df,
    "payments": payments_df,
    "reviews": reviews_df,
    "orders": orders_df,
    "products": products_df,
    "sellers": sellers_df,
    "category": category_df
}.items():

    print(f"\n{name.upper()}")
    print("Shape:", df.shape)
    print("Missing:", df.isnull().sum().sum())
    print("Duplicates:", df.duplicated().sum())

HOTEL
Shape: (119390, 31)
Missing: 0
Duplicates: 32001

CUSTOMERS
Shape: (99441, 5)
Missing: 0
Duplicates: 0

GEOLOCATION
Shape: (738332, 5)
Missing: 0
Duplicates: 0

ORDER_ITEMS
Shape: (112650, 7)
Missing: 0
Duplicates: 0

PAYMENTS
Shape: (103886, 5)
Missing: 0
Duplicates: 0

REVIEWS
Shape: (99224, 7)
Missing: 0
Duplicates: 0

ORDERS
Shape: (99441, 8)
Missing: 4908
Duplicates: 0

PRODUCTS
Shape: (32951, 9)
Missing: 0
Duplicates: 0

SELLERS
Shape: (3095, 4)
Missing: 0
Duplicates: 0

CATEGORY
Shape: (71, 2)
Missing: 0
Duplicates: 0

## Explanation of Duplicate Count Changes After Data Cleaning

Trong quá trình tiền xử lý dữ liệu, số lượng bản ghi trùng lặp (duplicate records) của bảng `hotel_bookings` thay đổi từ **31,994** lên **32,001** bản ghi. Sự thay đổi này không phải do dữ liệu mới được tạo ra mà là kết quả của quá trình chuẩn hóa dữ liệu.

Ban đầu, dữ liệu được tải từ file gốc vào dictionary `dfs`:

```python
dfs["hotel_bookings"]
```

Tại thời điểm này, số lượng bản ghi trùng lặp được xác định là:

```text
31,994 duplicate records
```

Để bảo toàn dữ liệu gốc, một bản sao độc lập được tạo bằng phương thức `.copy()`:

```python
hotel_df = dfs["hotel_bookings"].copy()
```

Khi đó:

```text
dfs["hotel_bookings"]  -> 31,994 duplicates
hotel_df              -> 31,994 duplicates
```

Sau đó, các bước làm sạch dữ liệu được thực hiện trên `hotel_df`:

```python
hotel_df.drop(columns=["company"], inplace=True)

hotel_df["agent"] = hotel_df["agent"].fillna(0)

hotel_df["country"] = hotel_df["country"].fillna("Unknown")

hotel_df["children"] = hotel_df["children"].fillna(0)
```

Các thao tác này làm thay đổi cách Pandas nhận diện các bản ghi trùng lặp. Trước khi làm sạch, một số bản ghi có thể khác nhau do:

* Giá trị NULL trong các cột `agent`, `country` hoặc `children`.
* Giá trị khác nhau trong cột `company`.

Sau khi thay thế các giá trị thiếu và loại bỏ cột `company`, một số bản ghi trước đây được xem là khác nhau trở thành hoàn toàn giống nhau trên tất cả các thuộc tính còn lại. Vì vậy, Pandas nhận diện thêm **7 bản ghi trùng lặp**, làm tổng số duplicate tăng từ:

```text
31,994 → 32,001
```

Lưu ý rằng dữ liệu gốc trong `dfs["hotel_bookings"]` không bị thay đổi nhờ sử dụng `.copy()`. Do đó:

```python
dfs["hotel_bookings"].duplicated().sum()
```

vẫn trả về:

```text
31,994
```

trong khi:

```python
hotel_df.duplicated().sum()
```

trả về:

```text
32,001
```

Đối với bước xử lý duplicate, giá trị cần sử dụng là **32,001**, vì đây là số lượng bản ghi trùng lặp của tập dữ liệu sau khi đã hoàn thành quá trình làm sạch. Đây cũng là tập dữ liệu sẽ được sử dụng cho các bước phân tích dữ liệu, trực quan hóa và xây dựng mô hình Machine Learning tiếp theo.

In [31]:
import os
os.makedirs("../data/clean", exist_ok=True)


hotel_df.to_csv(
    "../data/clean/hotel_bookings_clean.csv",
    index=False
)

customers_df.to_csv(
    "../data/clean/customers_clean.csv",
    index=False
)

geolocation_df.to_csv(
    "../data/clean/geolocation_clean.csv",
    index=False
)

order_items_df.to_csv(
    "../data/clean/order_items_clean.csv",
    index=False
)

payments_df.to_csv(
    "../data/clean/payments_clean.csv",
    index=False
)

reviews_df.to_csv(
    "../data/clean/reviews_clean.csv",
    index=False
)

orders_df.to_csv(
    "../data/clean/orders_clean.csv",
    index=False
)

products_df.to_csv(
    "../data/clean/products_clean.csv",
    index=False
)

sellers_df.to_csv(
    "../data/clean/sellers_clean.csv",
    index=False
)

category_df.to_csv(
    "../data/clean/category_translation_clean.csv",
    index=False
)

print("All cleaned datasets have been saved successfully!")

All cleaned datasets have been saved successfully!